// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Alias struct {
	ID   int64
	Name string
}

type AuthorsBook struct {
	AuthorID int64
	BookID   int64
}

type Book struct {
	ID          int64
	Title       string
	ReleaseYear sql.NullInt64
}

type BookStatus struct {
	BookID     int64
	LastPlayed sql.NullTime
	Status     int64
}

type BooksAlias struct {
	BookID  int64
	AliasID int64
}

type BooksFile struct {
	ID             int64
	SequenceNumber sql.NullInt64
	ConcreteBookID int64
	FileID         int64
}

type ConcreteBook struct {
	ID            int64
	BookID        int64
	ParentPathID  int64
	YearAudiobook sql.NullInt64
}

type File struct {
	ID           int64
	Name         string
	Extension    string
	Seconds      int64
	ParentPathID int64
	Checksum     sql.NullString
	Filesize     sql.NullInt64
}

type FileProgress struct {
	FileID  int64
	Seconds int64
}

type NarratorsBook struct {
	NarratorID int64
	BookID     int64
}

type Path struct {
	ID   int64
	Path string
}

type Person struct {
	ID   int64
	Name string
}

type PersonsAlias struct {
	PersonID int64
	AliasID  int64
}

type Series struct {
	ID   int64
	Name string
}

type SeriesAlias struct {
	SeriesID int64
	AliasID  int64
}

type SeriesBook struct {
	SeriesID       int64
	BookID         int64
	SequenceNumber sql.NullInt64
}

type StatusLabel struct {
	ID    int64
	Label string
}
